do $test$
declare
 t1 uuid:=gen_random_uuid();t2 uuid:=gen_random_uuid();c1 uuid:=gen_random_uuid();c2 uuid:=gen_random_uuid();
 s1 uuid:=gen_random_uuid();s2 uuid:=gen_random_uuid();sc1 uuid:=gen_random_uuid();sc2 uuid:=gen_random_uuid();
 r1 uuid:=gen_random_uuid();r2 uuid:=gen_random_uuid();r3 uuid:=gen_random_uuid();
 a uuid;appointment uuid;cid uuid;mid uuid;group_id uuid;asset jsonb;msg jsonb;grp jsonb;result jsonb;payload jsonb;old_epoch uuid;n int:=0;v bigint;
begin
 begin
  insert into auth.users(id,aud,role,email,email_confirmed_at) values(t1,'authenticated','authenticated',t1||'@example.invalid',now()),(t2,'authenticated','authenticated',t2||'@example.invalid',now()),(c1,'authenticated','authenticated',c1||'@example.invalid',now()),(c2,'authenticated','authenticated',c2||'@example.invalid',now());
  insert into auth.sessions(id,user_id) values(s1,t1),(s2,t2),(sc1,c1),(sc2,c2);
  insert into public.trainer_profiles(user_id,display_name,approval_status) values(t1,'Trainer One','approved'),(t2,'Trainer Two','approved');
  insert into public.trainer_client_relationships(id,trainer_id,client_id,state,accepted_at,activated_at) values(r1,t1,c1,'active',now(),now()),(r2,t2,c1,'active',now(),now()),(r3,t1,c2,'active',now(),now());
  insert into public.trainer_client_permissions(relationship_id,scope) select rid,scope from unnest(array[r1,r2,r3]) rid cross join unnest(array['workouts','sessions','messaging']) scope;
  set constraints all immediate;set constraints all deferred;
  result:=trainerhq_private.api(t1,s1,'assignment.create',jsonb_build_object('operation_id',gen_random_uuid(),'relationship_id',r1,'title','Assigned Workout','due_date','2099-01-02','exercises','[{"name":"Squat","sets":[{"reps":8,"weight":30,"done":false}]}]'::jsonb));
  a:=(result->>'id')::uuid;
  if a is null then raise exception 'Assignment missing';end if;n:=n+1;
  begin perform trainerhq_private.api(t2,s2,'assignment.accept',jsonb_build_object('operation_id',gen_random_uuid(),'assignment_id',a));raise exception 'Trainer accepted client assignment';exception when insufficient_privilege then n:=n+1;end;
  payload:=jsonb_build_object('operation_id',gen_random_uuid(),'assignment_id',a);
  perform trainerhq_private.api(c1,sc1,'assignment.accept',payload);perform trainerhq_private.api(c1,sc1,'assignment.accept',payload);
  if (select count(*) from public.workout_plans where trainer_assignment_id=a and user_id=c1) is distinct from 1 then raise exception 'Assignment plan duplication';end if;n:=n+1;
  perform set_config('request.jwt.claim.sub',c2::text,true);perform set_config('request.jwt.claims',jsonb_build_object('sub',c2,'session_id',sc2,'role','authenticated')::text,true);set local role authenticated;
  begin insert into public.workout_sessions(user_id,workout_name,trainer_assignment_id) values(c2,'Forged',a);raise exception 'Cross-client assignment FK bypass';exception when foreign_key_violation then n:=n+1;end;
  reset role;
  payload:=jsonb_build_object('operation_id',gen_random_uuid(),'relationship_id',r1,'start_at','2099-01-02T10:00:00Z','end_at','2099-01-02T11:00:00Z','assignment_id',a);
  result:=trainerhq_private.api(t1,s1,'schedule.create',payload);appointment:=(result->>'id')::uuid;
  if appointment is null then raise exception 'Appointment missing';end if;n:=n+1;
  if trainerhq_private.api(t1,s1,'schedule.create',payload) is distinct from result then raise exception 'Schedule retry duplicated';end if;n:=n+1;
  begin perform trainerhq_private.api(t2,s2,'schedule.create',payload||jsonb_build_object('operation_id',gen_random_uuid(),'relationship_id',r2,'assignment_id',null));raise exception 'Client double booking';exception when unique_violation then n:=n+1;end;
  begin perform trainerhq_private.api(t1,s1,'schedule.create',payload||jsonb_build_object('operation_id',gen_random_uuid(),'relationship_id',r3,'assignment_id',null));raise exception 'Trainer double booking';exception when unique_violation then n:=n+1;end;
  begin perform trainerhq_private.api(t1,s1,'schedule.update',payload||jsonb_build_object('operation_id',gen_random_uuid(),'id',appointment,'version',999));raise exception 'Stale schedule update';exception when unique_violation then n:=n+1;end;
  result:=trainerhq_private.api(c1,sc1,'schedule.list','{"from":"2099-01-02T00:00:00Z","until":"2099-01-03T00:00:00Z"}');
  if jsonb_array_length(result) is distinct from 1 then raise exception 'Client schedule unavailable';end if;n:=n+1;
  result:=trainerhq_private.api(c2,sc2,'schedule.list','{"from":"2099-01-02T00:00:00Z","until":"2099-01-03T00:00:00Z"}');
  if jsonb_array_length(result) is distinct from 0 then raise exception 'Other client schedule leak';end if;n:=n+1;
  result:=trainerhq_private.api(c1,sc1,'schedule.request_change',jsonb_build_object('operation_id',gen_random_uuid(),'id',appointment,'reason','Test time change'));
  perform trainerhq_private.api(t1,s1,'schedule.decline_change',jsonb_build_object('operation_id',gen_random_uuid(),'id',result->>'id'));
  if (select resolution from public.trainer_appointment_changes where id=(result->>'id')::uuid) is distinct from 'declined' then raise exception 'Change request failed';end if;n:=n+1;
  result:=trainerhq_private.api(t1,s1,'messages.open',jsonb_build_object('operation_id',gen_random_uuid(),'relationship_id',r1));cid:=(result->>'conversation_id')::uuid;
  payload:=jsonb_build_object('operation_id',gen_random_uuid(),'conversation_id',cid,'text','Synthetic test message');
  msg:=trainerhq_private.api(t1,s1,'messages.send',payload);mid:=(msg->>'id')::uuid;
  if trainerhq_private.api(t1,s1,'messages.send',payload) is distinct from msg or (select count(*) from public.trainer_messages where conversation_id=cid) is distinct from 1 then raise exception 'Message duplicate';end if;n:=n+1;
  result:=trainerhq_private.api(c1,sc1,'messages.threads','{}');
  if (result->0->>'unread_count')::int is distinct from 1 then raise exception 'Unread count incorrect';end if;n:=n+1;
  perform trainerhq_private.api(c1,sc1,'messages.read',jsonb_build_object('operation_id',gen_random_uuid(),'conversation_id',cid));
  result:=trainerhq_private.api(c1,sc1,'messages.threads','{}');
  if (result->0->>'unread_count')::int is distinct from 0 then raise exception 'Read cursor failed';end if;n:=n+1;
  if not exists(select 1 from public.trainer_message_receipts where message_id=mid and recipient_id=c1 and read_at is not null and delivered_at is not null) then raise exception 'Read timestamp missing';end if;n:=n+1;
  begin perform trainerhq_private.api(t2,s2,'messages.list',jsonb_build_object('conversation_id',cid));raise exception 'Other trainer conversation leak';exception when insufficient_privilege then n:=n+1;end;
  asset:=trainerhq_private.api(t1,s1,'media.reserve',jsonb_build_object('operation_id',gen_random_uuid(),'message_id',mid,'mime_type','image/jpeg','byte_count',8));
  perform set_config('request.jwt.claim.sub',t1::text,true);perform set_config('request.jwt.claims',jsonb_build_object('sub',t1,'session_id',s1,'role','authenticated')::text,true);set local role authenticated;
  insert into storage.objects(bucket_id,name,metadata) values('trainerhq-message-attachments',asset->>'object_path','{"size":8,"mimetype":"image/jpeg"}');n:=n+1;
  reset role;
  perform trainerhq_private.api(t1,s1,'media.complete',jsonb_build_object('operation_id',gen_random_uuid(),'id',asset->>'id'));
  if not exists(select 1 from public.trainer_message_attachments where id=(asset->>'id')::uuid and state='ready') then raise exception 'Attachment finalize failed';end if;n:=n+1;
  perform set_config('request.jwt.claim.sub',c2::text,true);perform set_config('request.jwt.claims',jsonb_build_object('sub',c2,'session_id',sc2,'role','authenticated')::text,true);set local role authenticated;
  if exists(select 1 from storage.objects where name=asset->>'object_path') then raise exception 'Nonmember Storage leak';end if;n:=n+1;
  reset role;
  grp:=trainerhq_private.api(c1,sc1,'messages.create_group',jsonb_build_object('operation_id',gen_random_uuid(),'title','Client-led group','relationship_ids',jsonb_build_array(r1,r2)));group_id:=(grp->>'conversation_id')::uuid;
  begin perform trainerhq_private.api(t1,s1,'messages.list',jsonb_build_object('conversation_id',group_id));raise exception 'Unaccepted group membership';exception when insufficient_privilege then n:=n+1;end;
  perform trainerhq_private.api(t1,s1,'messages.join',jsonb_build_object('operation_id',gen_random_uuid(),'conversation_id',group_id));
  perform trainerhq_private.api(t2,s2,'messages.join',jsonb_build_object('operation_id',gen_random_uuid(),'conversation_id',group_id));
  perform trainerhq_private.api(c1,sc1,'messages.send',jsonb_build_object('operation_id',gen_random_uuid(),'conversation_id',group_id,'text','Shared group history'));
  select channel_epoch into old_epoch from public.trainer_conversations where id=group_id;
  -- Keeping messaging while replacing other scopes must not accidentally revoke a group.
  select version into v from public.trainer_client_relationships where id=r1;
  perform trainerhq_private.api(c1,sc1,'relationship.update',jsonb_build_object('operation_id',gen_random_uuid(),'relationship_id',r1,'version',v,'state','active','scopes',jsonb_build_array('messaging','sessions','workouts','nutrition')));
  set constraints all immediate;set constraints all deferred;
  if not trainerhq_private.message_access(t1,group_id) then raise exception 'Scope replacement removed unchanged messaging';end if;n:=n+1;
  select version into v from public.trainer_client_relationships where id=r1;
  perform trainerhq_private.api(c1,sc1,'relationship.update',jsonb_build_object('operation_id',gen_random_uuid(),'relationship_id',r1,'version',v,'state','revoked'));
  set constraints all immediate;set constraints all deferred;
  if trainerhq_private.message_access(t1,group_id) or trainerhq_private.message_access(t1,cid) then raise exception 'Revoked trainer history access';end if;n:=n+1;
  if not trainerhq_private.message_access(t2,group_id) or not trainerhq_private.message_access(c1,group_id) then raise exception 'Other group members lost access';end if;n:=n+1;
  if (select count(*) from public.trainer_messages where conversation_id=group_id) is distinct from 1 then raise exception 'History deleted';end if;n:=n+1;
  if (select state from public.trainer_conversations where id=group_id) is distinct from 'open' then raise exception 'Group incorrectly archived';end if;n:=n+1;
  if (select channel_epoch from public.trainer_conversations where id=group_id)=old_epoch then raise exception 'Group epoch unchanged';end if;n:=n+1;
  perform trainerhq_private.api(t2,s2,'messages.send',jsonb_build_object('operation_id',gen_random_uuid(),'conversation_id',group_id,'text','Remaining discussion'));n:=n+1;
  begin perform trainerhq_private.api(t1,s1,'messages.send',payload);raise exception 'Idempotency response leaked after revocation';exception when insufficient_privilege then n:=n+1;end;
  perform set_config('request.jwt.claim.sub',t1::text,true);perform set_config('request.jwt.claims',jsonb_build_object('sub',t1,'session_id',s1,'role','authenticated')::text,true);set local role authenticated;
  if exists(select 1 from public.trainer_messages where conversation_id in(cid,group_id)) then raise exception 'RLS old message leak';end if;n:=n+1;
  if exists(select 1 from storage.objects where name=asset->>'object_path') then raise exception 'Revoked attachment leak';end if;n:=n+1;
  begin insert into storage.objects(bucket_id,name,metadata) values('trainerhq-message-attachments','forged','{}');raise exception 'Unreserved object upload allowed';exception when insufficient_privilege then n:=n+1;end;
  reset role;
  raise sqlstate 'ZX003';
 exception when sqlstate 'ZX003' then null;end;
 if exists(select 1 from auth.users where id in(t1,t2,c1,c2)) then raise exception 'Fixture cleanup failed';end if;n:=n+1;
 perform set_config('trainerhq.domain_test_count',n::text,true);
end $test$;
select 'passed' as result,current_setting('trainerhq.domain_test_count')::int as assertions;
